
services:
  database:
    image: postgres
    container_name: postgres-medical
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medical_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d medical_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: medical-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/medical_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: 06aa70fda6fbbb78be190baaae7122d6a0accc24c717bcdd6d845d59f1fbcc524d62f8d75615cf0fcce6bae4dd48af41d657a85cf6b5518ce33b4638f28b0f84
    volumes:
      - ./logs:/app/logs # Mount a volume for application logs

volumes:
  postgres_data:
